ALTER TABLE "Clip"
RENAME COLUMN  "clipUrl" TO "videoUrl";
ALTER TABLE "Clip"
ADD COLUMN     "description" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "duration" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "endTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "headline" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "payload" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "startTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "tags" TEXT[];
