version: '3'
services:
  pgsql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DATABASE: flashcast
      POSTGRES_USER: flashcast
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flashcast
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - flashcast
networks:
  flashcast:
    driver: bridge
volumes:
  pgdata:
  redisdata:
