services:
  pyapp:
    build: ../apps/clip-generator
    image: flashcasteval.azurecr.io/flashcast-pyapp:v1
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - ../apps/clip-generator:/app
    networks:
      - flashcast
  nextapp:
    build:
      context: ../
      dockerfile: ./deploy/nextapp/Dockerfile
    image: flashcastcr.azurecr.io/flashcast-nextapp:v1.3.3-dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ../apps/portal/.env.production.local:/app/apps/portal/.next/standalone/.env.local
    networks:
      - flashcast
  pgsql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DATABASE: flashcast
      POSTGRES_USER: flashcast
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flashcast
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - flashcast
networks:
  flashcast:
    driver: bridge
volumes:
  pgdata:
  redisdata:
